// muiIcons.js

// muiIcons.js

import {
  ConnectingAirportsRounded as PlaneIcon,
  LocationCityRounded as BuildingIcon,
  StarsRounded as StarCircleIcon,
  FlagCircleRounded as FlagIcon,
  VerifiedRounded as VerifiedIcon,
  AppShortcutRounded as PhoneStarsIcon,
  FaceRetouchingNaturalRounded as FaceStarIcon,
  FastfoodRounded as FastFoodIcon,
  LocalDiningRounded as SpoonForkIcon,
  LocalBarRounded as LiquorIcon,
  LunchDiningRounded as BurgerIcon,
  LocalCafeRounded as CoffeeIcon,
  CakeRounded as CakeIcon,
  FitnessCenterRounded as GymIcon,
  SportsGymnasticsRounded as SportsGymIcon,
  SwapHorizRounded as SwapIcon,
  AccountBalanceRounded as BankIcon,
  SavingsRounded as SavingsIcon,
  AccountBalanceWalletRounded as WalletIcon,
  RestaurantRounded as SpoonForkVerticalIcon,
  ShoppingBasketRounded as ShoppingBasketIcon,
  PersonalVideoRounded as TVIcon,
  DirectionsBusRounded as BusIcon,
  DirectionsCarRounded as CarIcon,
  PedalBikeRounded as BikeIcon,
  DeliveryDiningRounded as MotorcycleIcon,
  TrainRounded as TrainIcon,
  ImportContactsRounded as BookIcon,
  CardGiftcardRounded as PresentIcon,
  BathtubRounded as BathIcon,
  FilterVintageRounded as FlowerIcon,
  WifiRounded as WifiIcon,
  LocalPhoneRounded as PhoneIcon,
  PolicyRounded as LegalIcon,
  FavoriteRounded as LoveIcon,
  HandymanRounded as HammerIcon,
  PetsRounded as PetIcon,
  AutoGraphRounded as StockIcon,
  CheckroomRounded as ClothesIcon,
  SettingsRounded as MechanicalWheelIcon,
  Payments as CashIcon,
  AccountBalance as BankAltIcon,
  AutoAwesomeRounded as GeneralIcon,
  WalletRounded as InvestmentIcon,
  MonetizationOnRounded as LoanIcon,
  CreditCardRounded as CardIcon,
  HealthAndSafetyRounded as InsuranceIcon,
  PixRounded as EMoneyIcon,
} from '@mui/icons-material';

import HomeIcon from "@mui/icons-material/Home";
import WorkIcon from "@mui/icons-material/Work";
import SchoolIcon from "@mui/icons-material/School";
import ShoppingCartIcon from "@mui/icons-material/ShoppingCart";
import FitnessCenterIcon from "@mui/icons-material/FitnessCenter";
import RestaurantIcon from "@mui/icons-material/Restaurant";
import LocalLibraryIcon from "@mui/icons-material/LocalLibrary";
import DirectionsCarIcon from "@mui/icons-material/DirectionsCar";
import LocalHospitalIcon from "@mui/icons-material/LocalHospital";
import MovieIcon from "@mui/icons-material/Movie";
import CardGiftcardIcon from "@mui/icons-material/CardGiftcard";

export const CategoryIcons = {
  Plane: PlaneIcon,
  Building: BuildingIcon,
  StarCircle: StarCircleIcon,
  Flag: FlagIcon,
  Verified: VerifiedIcon,
  PhoneStars: PhoneStarsIcon,
  FaceStar: FaceStarIcon,
  FastFood: FastFoodIcon,
  SpoonFork: SpoonForkIcon,
  Liquor: LiquorIcon,
  Burger: BurgerIcon,
  Coffee: CoffeeIcon,
  Cake: CakeIcon,
  Gym: GymIcon,
  SportsGym: SportsGymIcon,
  Swap: SwapIcon,
  Bank: BankIcon,
  Savings: SavingsIcon,
  Wallet: WalletIcon,
  SpoonForkVertical: SpoonForkVerticalIcon,
  ShoppingBasket: ShoppingBasketIcon,
  TV: TVIcon,
  Bus: BusIcon,
  Car: CarIcon,
  Bike: BikeIcon,
  Motorcycle: MotorcycleIcon,
  Train: TrainIcon,
  Book: BookIcon,
  Present: PresentIcon,
  Bath: BathIcon,
  Flower: FlowerIcon,
  Wifi: WifiIcon,
  Phone: PhoneIcon,
  Legal: LegalIcon,
  Love: LoveIcon,
  Hammer: HammerIcon,
  Pet: PetIcon,
  Stock: StockIcon,
  Clothes: ClothesIcon,
  MechanicalWheel: MechanicalWheelIcon,
  Cash: CashIcon,
  BankAlt: BankAltIcon,
  General: GeneralIcon,
  Investment: InvestmentIcon,
  Loan: LoanIcon,
  Card: CardIcon,
  Insurance: InsuranceIcon,
  EMoney: EMoneyIcon,
  Home: HomeIcon,
  Work: WorkIcon,
  School: SchoolIcon,
  ShoppingCart: ShoppingCartIcon,
  FitnessCenter: FitnessCenterIcon,
  Restaurant: RestaurantIcon,
  LocalLibrary: LocalLibraryIcon,
  DirectionsCar: DirectionsCarIcon,
  LocalHospital: LocalHospitalIcon,
  Movie: MovieIcon,
  GiftCard: CardGiftcardIcon
};


export default CategoryIcons